package populous2

import (
	"crypto/sha256"
	"fmt"
	legacy "go-populous2/internal/legacy"
	"testing"
)

// Each reference was generated by the original native cast routine on empty
// flat ground. Both the complete tile map and final 32-bit RNG are checked.
func TestGroundEffectsAgainstOriginal68000Routines(t *testing.T) {
	for _, reference := range []struct {
		id        SpellID
		seed, rng uint32
		digest    string
	}{
		{Baptism, 0, 2220603294, "0ecd3ce53d7b8b4744a038cbad6ede222cff491ddd26e0ec1f6d44a0a78e8e3a"},
		{Baptism, 4311, 810914655, "b5b9c835c6e4bc26b2a57885a85809023c0989fd81da0b70975ff26393f78670"},
		{Baptism, 65536, 3997696, "1cad9a8d9165161f5af1be989844e3baef5a7d9063da94281b80e9cc20c798f1"},
		{Swamp, 0, 2220603294, "4307982f01f94f2e1366a0db536fe0a710c423eda6b3cd58a8fa5e6e980d6d77"},
		{Swamp, 4311, 810914655, "76b32ce738712d8e26a13d49074e909b50f59318bd6dd93b5c69156240fccdc0"},
		{Swamp, 65536, 3997696, "5d1a2a5cd1a1527a278688a8e08aa4cc0127b618b62c47d3960bffded4fee1cb"},
		{Flowers, 0, 2220603294, "f874fe8590612e3cddab6d927cd11fe69d5ab0c9e947fcec02b7046039e6aa9b"},
		{Flowers, 4311, 810914655, "0ee2081f238d3676ad393e35d639fcde7e4795f0f404dfeb76cf23e1428fe62a"},
		{Flowers, 65536, 3997696, "510b19ca0ac4512a07f19f5eec0595207ecd4b232647730fad73a415d4a8f710"},
	} {
		w := flatGroundWorld(t)
		s := w.Core.Snapshot()
		s.RNG = reference.seed
		w.Core = legacy.WorldFromSnapshot(s, w.Core.Rules)
		if !w.Cast(0, reference.id, Target{X: 32, Y: 32}) {
			t.Fatal("native reference cast rejected")
		}
		var tiles [4096]byte
		for i := range tiles {
			tiles[i] = w.TerrainCell(i%64, i/64).Code
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(tiles[:])); got != reference.digest {
			t.Fatalf("power %d seed %d tile mismatch: %s", reference.id, reference.seed, got)
		}
		if w.Core.Snapshot().RNG != reference.rng {
			t.Fatal("native cast consumed a different random sequence")
		}
	}
}

func flatGroundWorld(t *testing.T) *World {
	t.Helper()
	w, err := NewWorld(testBundle(t), 0, true)
	if err != nil {
		t.Fatal(err)
	}
	for i := range w.Core.Alt {
		w.Core.Alt[i] = 1
	}
	for i := range w.Core.MapBlk {
		w.Core.MapBlk[i] = legacy.FlatBlock
		w.Core.MapAlt[i] = 0
		w.Core.MapBk2[i] = 0
		w.Core.MapWho[i] = 0
	}
	w.Core.Peeps = nil
	w.Core.Magnets[0].Mana = 1000000
	return w
}

func TestNativeGroundCastTablesAndPersistence(t *testing.T) {
	for _, id := range []SpellID{Baptism, Swamp, Flowers} {
		w := flatGroundWorld(t)
		if !w.Cast(0, id, Target{X: 32, Y: 32}) {
			t.Fatalf("ground cast %d rejected", id)
		}
		count := 0
		for pos, mark := range w.Marks {
			if !mark.Persistent {
				continue
			}
			count++
			if mark.Spell != id || mark.NativeTile == 0 || distance(pos, 32+32*64) > 4 {
				t.Fatal("native ground footprint invalid")
			}
			if got := w.TerrainCell(pos%64, pos/64).Tile(0, 0, 0); got != int(mark.NativeTile) {
				t.Fatal("native ground graphic not selected")
			}
		}
		if count == 0 || count >= 45 {
			t.Fatalf("native sampling replaced with a filled area: %d", count)
		}
		for range 300 {
			w.tickEffects()
		}
		for _, mark := range w.Marks {
			if mark.Persistent && mark.Life != 1 {
				t.Fatal("persistent original ground effect expired")
			}
		}
		restored, err := Restore(testBundle(t), w.Snapshot())
		if err != nil || restored.Marks != w.Marks {
			t.Fatalf("ground effect save failed: %v", err)
		}
	}
}

func TestFontsChangeEitherFaithOncePerEntry(t *testing.T) {
	w := flatGroundWorld(t)
	w.Marks[2000] = Mark{Spell: Baptism, Player: 0, Life: 1, Persistent: true, NativeTile: 143}
	w.Marks[2001] = w.Marks[2000]
	w.Core.Peeps = []legacy.Peep{{Player: 0, Population: 100, AtPos: 2000, Flags: legacy.OnMove}}
	w.applyGroundEffects()
	if w.Core.Peeps[0].Player != 1 {
		t.Fatal("font did not reverse friendly faith")
	}
	w.applyGroundEffects()
	if w.Core.Peeps[0].Player != 1 {
		t.Fatal("stationary group converted repeatedly")
	}
	w.Core.Peeps[0].AtPos = 2001
	w.applyGroundEffects()
	if w.Core.Peeps[0].Player != 0 {
		t.Fatal("adjacent font did not reverse faith again")
	}
	w.Core.Peeps[0].AtPos = 2002
	w.applyGroundEffects()
	w.Core.Peeps[0].AtPos = 2001
	w.applyGroundEffects()
	if w.Core.Peeps[0].Player != 1 {
		t.Fatal("reentry into a font ignored")
	}
}

func TestSwampsKillWalkersOfBothSides(t *testing.T) {
	w := flatGroundWorld(t)
	w.Marks[2000] = Mark{Spell: Swamp, Player: 0, Life: 1, Persistent: true, NativeTile: 168}
	w.Core.Peeps = []legacy.Peep{{Player: 0, Population: 100, AtPos: 2000, Flags: legacy.OnMove}, {Player: 1, Population: 100, AtPos: 2000, Flags: legacy.OnMove}}
	w.applyGroundEffects()
	if w.Core.Peeps[0].Population != 0 || w.Core.Peeps[1].Population != 0 {
		t.Fatal("swamp restricted to caster's enemy")
	}
}
