package populous2

import (
	"crypto/sha256"
	"fmt"
	legacy "go-populous2/internal/legacy"
	"testing"
)

// Each reference was generated by the original native cast routine on empty
// flat ground. Both the complete tile map and final 32-bit RNG are checked.
func TestGroundEffectsAgainstOriginal68000Routines(t *testing.T) {
	for _, reference := range []struct {
		id        SpellID
		seed, rng uint32
		digest    string
	}{
		{Baptism, 0, 2220603294, "0ecd3ce53d7b8b4744a038cbad6ede222cff491ddd26e0ec1f6d44a0a78e8e3a"},
		{Baptism, 4311, 810914655, "b5b9c835c6e4bc26b2a57885a85809023c0989fd81da0b70975ff26393f78670"},
		{Baptism, 65536, 3997696, "1cad9a8d9165161f5af1be989844e3baef5a7d9063da94281b80e9cc20c798f1"},
		{Swamp, 0, 2220603294, "4307982f01f94f2e1366a0db536fe0a710c423eda6b3cd58a8fa5e6e980d6d77"},
		{Swamp, 4311, 810914655, "76b32ce738712d8e26a13d49074e909b50f59318bd6dd93b5c69156240fccdc0"},
		{Swamp, 65536, 3997696, "5d1a2a5cd1a1527a278688a8e08aa4cc0127b618b62c47d3960bffded4fee1cb"},
		{Flowers, 0, 2220603294, "f874fe8590612e3cddab6d927cd11fe69d5ab0c9e947fcec02b7046039e6aa9b"},
		{Flowers, 4311, 810914655, "0ee2081f238d3676ad393e35d639fcde7e4795f0f404dfeb76cf23e1428fe62a"},
		{Flowers, 65536, 3997696, "510b19ca0ac4512a07f19f5eec0595207ecd4b232647730fad73a415d4a8f710"},
	} {
		w := flatGroundWorld(t)
		s := w.Core.Snapshot()
		s.RNG = reference.seed
		w.Core = legacy.WorldFromSnapshot(s, w.Core.Rules)
		if !w.Cast(0, reference.id, Target{X: 32, Y: 32}) {
			t.Fatal("native reference cast rejected")
		}
		var tiles [4096]byte
		for i := range tiles {
			tiles[i] = w.TerrainCell(i%64, i/64).Code
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(tiles[:])); got != reference.digest {
			t.Fatalf("power %d seed %d tile mismatch: %s", reference.id, reference.seed, got)
		}
		if w.Core.Snapshot().RNG != reference.rng {
			t.Fatal("native cast consumed a different random sequence")
		}
	}
}

func flatGroundWorld(t *testing.T) *World {
	t.Helper()
	w, err := NewWorld(testBundle(t), 0, true)
	if err != nil {
		t.Fatal(err)
	}
	// Controlled effect fixtures contain no gods' marker actors. Remove the
	// normal game markers along with the followers replaced below.
	for owner := 1; owner < NativeMagnetCount; owner++ {
		w.unlinkActor(NativeMagnetPool, owner)
	}
	w.NativeGlobals = NativeGlobalImage{}
	w.RecordImage = NativeRecordImage{}
	w.NativeEntries = [legacy.MaxPeeps]NativeFollowerEntry{}
	for i := range w.Core.Alt {
		w.Core.Alt[i] = 1
	}
	for i := range w.Core.MapBlk {
		w.Core.MapBlk[i] = legacy.FlatBlock
		w.Core.MapAlt[i] = 0
		w.Core.MapBk2[i] = 0
		w.Core.MapWho[i] = 0
	}
	w.Core.Peeps = nil
	w.Core.Magnets[0].Carried, w.Core.Magnets[1].Carried = 0, 0
	w.Core.Magnets[0].Mana = 1000000
	return w
}

func TestNativeGroundCastTablesAndPersistence(t *testing.T) {
	for _, id := range []SpellID{Baptism, Swamp, Flowers} {
		w := flatGroundWorld(t)
		if !w.Cast(0, id, Target{X: 32, Y: 32}) {
			t.Fatalf("ground cast %d rejected", id)
		}
		count := 0
		for pos, mark := range w.Marks {
			if !mark.Persistent {
				continue
			}
			count++
			if mark.Spell != id || mark.NativeTile == 0 || distance(pos, 32+32*64) > 4 {
				t.Fatal("native ground footprint invalid")
			}
			if got := w.TerrainCell(pos%64, pos/64).Tile(0, 0, 0); got != int(mark.NativeTile) {
				t.Fatal("native ground graphic not selected")
			}
		}
		if count == 0 || count >= 45 {
			t.Fatalf("native sampling replaced with a filled area: %d", count)
		}
		for range 300 {
			w.tickEffects()
		}
		for _, mark := range w.Marks {
			if mark.Persistent && mark.Life != 1 {
				t.Fatal("persistent original ground effect expired")
			}
		}
		restored, err := Restore(testBundle(t), w.Snapshot())
		if err != nil || restored.Marks != w.Marks {
			t.Fatalf("ground effect save failed: %v", err)
		}
	}
}

// tickGroundPrepassForTest runs the same terrain entry used by the follower
// dispatcher, without advancing unrelated movement or the campaign result.
func tickGroundPrepassForTest(t *testing.T, w *World) {
	t.Helper()
	for index := range w.Core.Peeps {
		if !w.NativeEntries[index].Initialized {
			w.initializeNativeFollower(index)
		}
	}
	for index := range w.Core.Peeps {
		if err := w.runNativeFollowerCall(func() error {
			_, err := w.CommonPrepass.Tick(nativeActorReference(NativeFollowerPool, index), w.nativeCommonPrepassCallbacks())
			return err
		}); err != nil {
			t.Fatal(err)
		}
	}
}

func TestFontsRetainAnimationBeforeChangingFaith(t *testing.T) {
	for _, player := range []byte{0, 1} {
		w := flatGroundWorld(t)
		w.Marks[2000] = Mark{Spell: Baptism, Player: 0, Life: 1, Persistent: true, NativeTile: 143}
		w.Core.Peeps = []legacy.Peep{{Player: player, Population: 100, AtPos: 2000, Flags: legacy.OnMove}}
		tickGroundPrepassForTest(t, w)
		ref := nativeActorReference(NativeFollowerPool, 0)
		a, _ := w.RecordImage.ReadFollowerEntry(ref)
		if a.Owner != player+1 || a.Motion.Kind != 14 || a.Motion.State != 0x36 || a.Motion.Population != 100 {
			t.Fatalf("font skipped the retained conversion animation: %+v; peep %+v", a, w.Core.Peeps[0])
		}
		initial := a.Motion.Animation
		tickGroundPrepassForTest(t, w)
		a, _ = w.RecordImage.ReadFollowerEntry(ref)
		if a.Motion.Animation != initial || a.Owner != player+1 {
			t.Fatal("terrain entry restarted or completed the conversion")
		}
		completed := false
		for range 100 {
			var step FollowerTerrainStep
			if err := w.runNativeFollowerCall(func() error {
				var err error
				step, err = w.FollowerTerrain.TickConversion(ref, w.nativeTerrainCallbacks())
				return err
			}); err != nil {
				t.Fatal(err)
			}
			if step.Search {
				completed = true
				break
			}
		}
		a, _ = w.RecordImage.ReadFollowerEntry(ref)
		if !completed || a.Owner != (player^1)+1 || a.Motion.Population != 100 || a.Motion.Kind != 2 || a.Motion.State != 2 {
			t.Fatal("native conversion did not finish with opposite faith and ordinary search")
		}
	}
}

func TestSwampsRetainDeathForWalkersOfBothSides(t *testing.T) {
	w := flatGroundWorld(t)
	w.Marks[2000] = Mark{Spell: Swamp, Player: 0, Life: 1, Persistent: true, NativeTile: 168}
	w.Core.Peeps = []legacy.Peep{{Player: 0, Population: 100, AtPos: 2000, Flags: legacy.OnMove}, {Player: 1, Population: 100, AtPos: 2000, Flags: legacy.OnMove}}
	tickGroundPrepassForTest(t, w)
	for index := range w.Core.Peeps {
		a, _ := w.RecordImage.ReadFollowerEntry(nativeActorReference(NativeFollowerPool, index))
		if a.Motion.Population != 0 || a.Owner != uint8(index+1) || a.Motion.Kind != 16 || a.Motion.State != 0x38 || !w.Occupancy.Followers[index].Linked {
			t.Fatalf("swamp did not retain the native death allocation and graph link: %+v; linked %v", a, w.Occupancy.Followers[index].Linked)
		}
	}
}
